In [1]:
import numpy as np
import pandas as pd
import json
import time
import datetime
import calendar

In [2]:
# load in psiturk data
rm1df = pd.read_json('../../data/db/exported/room1-2.8.19.json')
rm2df = pd.read_json('../../data/db/exported/room2-2.8.19.json')

# drop runs that didn't finish
rm1df = rm1df[rm1df.status != 1]
rm2df = rm2df[rm2df.status != 1]

# keep relevant columns
rm1df = rm1df[['uniqueid','datastring','beginhit','endhit','hitid','status']].reset_index(drop=True)
rm2df = rm2df[['uniqueid','datastring','beginhit','endhit','hitid','status']].reset_index(drop=True)

# convert datastring to dict 
rm1df['datastring'] = rm1df['datastring'].apply(json.loads)
rm2df['datastring'] = rm2df['datastring'].apply(json.loads)

# add test room column
rm1df['testroom'] = 1
rm2df['testroom'] = 2

# concatenate dataframes
expdf = pd.concat([rm1df, rm2df], ignore_index=True)

In [3]:
expdf

,uniqueid,datastring,beginhit,endhit,hitid,status,testroom
0,debugrcDp9:debugAniFb,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-02 22:31:54.578217,2018-10-02 23:35:38.071920,debugvPYXO,3,1
1,debugIEH2T:debugDLVLJ,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-12 18:14:31.394716,2018-10-12 19:12:06.999050,debug7rmxU,3,1
2,debugBUnNA:debugLtZcs,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-12 19:17:03.503575,2018-10-12 20:10:44.883411,debugTkKFp,3,1
3,debugd1YD1:debug4FrAg,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-12 20:22:07.319435,2018-10-12 21:09:46.566325,debugonOYk,3,1
4,debugGaDml:debugFTHoY,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-12 21:28:01.305584,2018-10-12 22:16:31.057617,debugXHY6O,3,1
5,debugGVTD3:debugfpzCT,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-12 22:59:26.829625,2018-10-13 00:01:24.711451,debuggQ0y6,3,1
6,debugokLIG:debugalG88,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-13 18:28:34.378931,2018-10-13 19:15:12.977411,debugslG65,3,1
7,debugdhnfF:debug6fW93,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-13 19:35:43.889748,2018-10-13 20:32:37.663906,debugszpCm,3,1
8,debugHKLdw:debugk43rK,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-13 20:37:43.034617,2018-10-13 21:27:38.367721,debugHGwAN,3,1
9,debugnj3ww:debugAC3on,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-13 21:34:31.560211,2018-10-13 22:25:03.538624,debughqOmP,3,1
10,debugmRWSb:debugPVXlB,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-13 22:36:59.470450,2018-10-13 23:39:04.416342,debugKyt7W,3,1
11,debug3lixg:debugdwpeu,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-13 23:58:52.853801,2018-10-14 00:49:19.357875,debugNPCaa,3,1
12,debugSlGFs:debug42TAZ,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-16 18:43:23.919675,2018-10-16 19:31:09.744949,debugRDfe2,3,1
13,debughbxU4:debugUuTk6,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-16 19:37:20.607109,2018-10-16 20:31:04.663568,debugQDztf,3,1
14,debugPWYYp:debugg9K3I,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-16 20:42:29.538168,2018-10-16 21:36:28.945087,debugy6cu7,3,1
15,debugjQumg:debugSascw,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-16 21:41:44.047611,2018-10-16 22:26:05.159753,debugZFxnA,3,1
16,debugScfXr:debugJN6fA,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-16 22:50:21.145527,2018-10-16 23:40:16.082236,debugCYT72,3,1
17,debugIFCgX:debugt0bgV,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-18 14:52:24.425282,2018-10-18 15:55:52.788902,debugD7OMi,3,1
18,debugQEynG:debugpwxCU,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-18 17:09:47.721500,2018-10-18 18:07:19.944406,debugzSZgD,3,1
19,debug2Ea7T:debugosNZ7,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-18 20:00:26.949390,2018-10-18 20:55:26.773396,debugrWVJB,3,1
20,debugBB0yq:debug30NBt,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-18 23:36:47.846224,2018-10-19 00:26:44.282091,debugPQRfi,3,1
21,debugxH6Hc:debughncuB,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-19 15:32:31.479807,2018-10-19 16:28:34.059428,debugGs8jX,3,1
22,debugbu5Bq:debugl91xD,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-19 18:30:28.663944,2018-10-19 19:16:44.987548,debugsjD9k,3,1
23,debugBhGxH:debugMWNLW,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-19 19:25:39.134717,2018-10-19 20:14:01.652563,debugAVKcW,3,1
24,debug6GN7B:debugBfGog,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-19 20:42:41.578907,2018-10-19 21:30:58.820248,debugU0uFZ,3,1
25,debug5vYxL:debug5nmdy,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-19 22:45:49.525782,2018-10-19 23:34:17.974753,debugt5ypJ,3,1
26,debugdHg9G:debugnb698,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-20 16:57:14.178075,2018-10-20 17:55:32.458968,debugUD0ms,3,1
27,debugXxDJj:debugwfW5a,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-20 19:11:07.473360,2018-10-20 20:01:31.411971,debugII2Xo,3,1
28,debugTFgpv:debugfK2JN,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-20 20:15:28.823106,2018-10-20 21:15:33.010013,debug8lbdL,3,1
29,debugVFMcA:debugjM9rk,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-20 21:22:30.703964,2018-10-20 22:18:55.936915,debugaz6TP,3,1
...,...,...,...,...,...,...,...
79,debugb8Mbo:debugWMuG3,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-19 18:31:19.601051,2018-10-19 19:18:53.588909,debugiEYko,3,2
80,debugVzPKf:debugbR0Vq,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-19 20:23:06.091565,2018-10-19 21:29:39.493564,debugol7OU,3,2
81,debugS5d5Q:debugpxU3l,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-20 17:11:15.010873,2018-10-20 18:01:28.914321,debugqqX98,3,2
82,debugNTcAd:debugiaabY,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-20 18:05:56.447266,2018-10-20 18:56:08.578210,debugJkXTc,3,2
83,debugVmS30:debugTvoFz,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-20 19:19:01.036352,2018-10-20 20:16:08.648875,debugKZIcf,3,2
84,debugmfo3M:debugCN3Vj,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-20 20:20:51.861989,2018-10-20 21:14:59.556348,debugqh216,3,2
85,debugRNwge:debugv0fyi,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-20 21:28:28.792497,2018-10-20 22:17:39.967758,debug0L0Oy,3,2
86,debugfO0us:debug6tlz1,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-21 23:19:44.803432,2018-10-22 00:23:24.515902,debugrctlv,3,2
87,debugLou4K:debug5KpMQ,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-22 16:51:53.390057,2018-10-22 17:40:58.713683,debugsx10t,3,2
88,debuglAycr:debugoFV0D,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-22 18:13:19.729907,2018-10-22 19:09:59.702632,debugNgrtk,3,2
89,debugHNBk3:debugUUMPo,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-22 19:17:01.779509,2018-10-22 20:07:04.697452,debugdWWks,3,2
90,debugohSU7:debugRz3rh,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-22 20:31:44.881569,2018-10-22 21:38:05.206211,debugOWRjW,3,2
91,debug67jbC:debugFuOd5,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-22 22:23:42.681643,2018-10-22 23:08:59.861848,debugCMbxH,3,2
92,debugWvhTI:debug65Thd,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-22 23:24:13.194309,2018-10-23 00:13:22.782005,debugJF0Wp,3,2
93,debugm7zD9:debugOLIFw,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-23 18:30:23.839666,2018-10-23 19:29:36.654793,debugf5gky,3,2
94,debugW3qVn:debugxspIb,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-23 19:42:51.543476,2018-10-23 20:45:55.867094,debugXjUBt,3,2
95,debug89P9i:debugM6pZC,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-23 20:52:09.380476,2018-10-23 21:51:15.973999,debugTCRGh,3,2
96,debugTYPE4:debugnAJ5U,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-23 22:58:02.839931,2018-10-23 23:49:14.143795,debugRG2lh,3,2
97,debugoAeJs:debug47jDd,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-28 16:34:32.511568,2018-10-28 17:52:26.238551,debugKK0U7,3,2
98,debugAlono:debugbY9Uu,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-28 19:55:23.218881,2018-10-28 20:50:23.398119,debugGBOki,3,2
99,debugYsNkJ:debug0AYus,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-28 22:06:57.545411,2018-10-28 23:05:44.007621,debug2D5mC,3,2
100,debugVk1WF:debugksIUE,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-28 23:32:03.505549,2018-10-29 00:23:09.765200,debugBgmvn,3,2
101,debugFL4Kc:debugPi0it,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-29 19:33:26.698755,2018-10-29 20:22:25.611807,debugbe5SC,3,2
102,debugAN3bL:debugJClT8,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-29 20:47:52.256760,2018-10-29 21:41:34.312890,debugs4E6X,3,2
103,debugTkyN6:debugdsr6W,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-30 00:34:19.043260,2018-10-30 01:24:36.564559,debugMdey9,3,2
104,debug5ytRS:debug22nvn,"{'condition': 0, 'counterbalance': 0, 'assignm...",2019-01-31 23:01:12.170466,2019-02-01 00:00:58.271323,debughWKN0,3,2
105,debugRQQWb:debugwDi2H,"{'condition': 0, 'counterbalance': 0, 'assignm...",2019-02-01 20:24:04.448255,2019-02-01 21:19:38.414725,debugU0Ils,3,2
106,debugo1MpX:debugfpXYH,"{'condition': 0, 'counterbalance': 0, 'assignm...",2019-02-01 22:48:31.811536,2019-02-01 23:50:55.654008,debugnMToQ,3,2
107,debugSeRNG:debug5pTo9,"{'condition': 0, 'counterbalance': 0, 'assignm...",2019-02-07 19:29:32.573721,2019-02-07 20:45:06.517044,debugvKGyP,3,2
108,debug41SJm:debugJW4AU,"{'condition': 0, 'counterbalance': 0, 'assignm...",2019-02-07 21:42:17.424466,2019-02-07 22:30:42.922183,debugWs4e3,3,2

In [10]:
# load pre/post questionnaire responses
preqdf = pd.read_csv('../../data/google-form-data/Pre-experiment Questionnaire.csv', parse_dates=[0])
preqdf = preqdf.rename(index=str, columns={'Timestamp':'preqtime'})
postqdf = pd.read_csv('../../data/google-form-data/Post-experiment questionnaire.csv', parse_dates=[0])
postqdf = postqdf.rename(index=str, columns={'Timestamp':'postqtime'})

# exclude test runs
preqdf = preqdf.dropna(subset=['Subject ID'], inplace=False).reset_index(drop=True)
postqdf = postqdf.dropna(subset=['Subject ID'], inplace=False).reset_index(drop=True)

# convert form timestamp to POSIX time **SERIES.APPLY(DT.DT.TIMESTAMP).MULTIPLY(1000) DOES NOT WORK**
newpretimestamp = pd.Series([0]*len(preqdf['preqtime']))
for ix, val in enumerate(newpretimestamp):
    newpretimestamp[ix] = preqdf['preqtime'][ix].timestamp()*1000
preqdf['preqtime'] = newpretimestamp

newposttimestamp = pd.Series([0]*len(postqdf['postqtime']))
for ix, val in enumerate(newposttimestamp):
    newposttimestamp[ix] = postqdf['postqtime'][ix].timestamp()*1000
postqdf['postqtime'] = newposttimestamp

### for mapping between Google Forms with experiment IDs and SQLite databases with PsiTurk IDs

In [30]:
def concat_data(turkdata, preform, postform):
    """
    matches between experiment data and pre/post questionnaire responses, concatenates dataframes
    """
    turktimes = {}
    preqtimes = {}
    for ix, sub in turkdata.iterrows():
        turktimes[ix] = sub['datastring']['data'][0]['dateTime']
    for ix, sub in preform.iterrows():
        preqtimes[ix] = preform['preqtime'][sub]
        
    for ix, subtime in turktimes.items():

SyntaxError: unexpected EOF while parsing (<ipython-input-30-d88114952d53>, line 10)

In [36]:
# add empty columns to 
expdf = pd.concat([expdf, pd.DataFrame(columns=newcols)], sort=False)

turktimes = {}
preqtimes = {}

# get psiturk start times
for ix, sub in expdf.iterrows():
    turktimes[sub['datastring']['data'][0]['dateTime']] = ix
# get gform submit times
for ix, sub in preqdf.iterrows():
    preqtimes[preqdf['preqtime'][sub]] = ix

# iterate over psiturk start times, find closest gform time
for turktime, ix in turktimes.items():
    closest = preqtimes.get(turktime, preqtimes[min(preqtimes.keys(), key=lambda k: abs(k-turktime))])

ValueError: cannot index with vector containing NA / NaN values

In [42]:
type(preqdf.loc[0])

pandas.core.series.Series

In [53]:
expdf.reindex([expdf, pd.DataFrame(columns=newcols)])

,uniqueid,datastring,beginhit,endhit,hitid,status,testroom,preqtime,Subject ID,"Outside of this study, have you ever watched an episode of either of the TV shows ""Atlanta"" or ""Arrested Development?""",...,What is/was your major?,How many hours of sleep did you get last night?,How many cups of coffee have you had today?,How alert are you feeling?,postqtime,How engaging did you find the episode?,How easy/difficult was it to follow the episode?,How well do you feel you recalled the events of the episode?,How well do you feel you learned the characters' names over the course of the episode?,How tired do you feel?
0,debugrcDp9:debugAniFb,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-02 22:31:54.578217,2018-10-02 23:35:38.071920,debugvPYXO,3.0,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,debugIEH2T:debugDLVLJ,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-12 18:14:31.394716,2018-10-12 19:12:06.999050,debug7rmxU,3.0,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,debugBUnNA:debugLtZcs,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-12 19:17:03.503575,2018-10-12 20:10:44.883411,debugTkKFp,3.0,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,debugd1YD1:debug4FrAg,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-12 20:22:07.319435,2018-10-12 21:09:46.566325,debugonOYk,3.0,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,debugGaDml:debugFTHoY,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-12 21:28:01.305584,2018-10-12 22:16:31.057617,debugXHY6O,3.0,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,debugGVTD3:debugfpzCT,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-12 22:59:26.829625,2018-10-13 00:01:24.711451,debuggQ0y6,3.0,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,debugokLIG:debugalG88,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-13 18:28:34.378931,2018-10-13 19:15:12.977411,debugslG65,3.0,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,debugdhnfF:debug6fW93,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-13 19:35:43.889748,2018-10-13 20:32:37.663906,debugszpCm,3.0,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,debugHKLdw:debugk43rK,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-13 20:37:43.034617,2018-10-13 21:27:38.367721,debugHGwAN,3.0,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,debugnj3ww:debugAC3on,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-13 21:34:31.560211,2018-10-13 22:25:03.538624,debughqOmP,3.0,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,debugmRWSb:debugPVXlB,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-13 22:36:59.470450,2018-10-13 23:39:04.416342,debugKyt7W,3.0,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,debug3lixg:debugdwpeu,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-13 23:58:52.853801,2018-10-14 00:49:19.357875,debugNPCaa,3.0,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,debugSlGFs:debug42TAZ,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-16 18:43:23.919675,2018-10-16 19:31:09.744949,debugRDfe2,3.0,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,debughbxU4:debugUuTk6,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-16 19:37:20.607109,2018-10-16 20:31:04.663568,debugQDztf,3.0,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,debugPWYYp:debugg9K3I,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-16 20:42:29.538168,2018-10-16 21:36:28.945087,debugy6cu7,3.0,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,debugjQumg:debugSascw,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-16 21:41:44.047611,2018-10-16 22:26:05.159753,debugZFxnA,3.0,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,debugScfXr:debugJN6fA,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-16 22:50:21.145527,2018-10-16 23:40:16.082236,debugCYT72,3.0,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,debugIFCgX:debugt0bgV,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-18 14:52:24.425282,2018-10-18 15:55:52.788902,debugD7OMi,3.0,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,debugQEynG:debugpwxCU,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-18 17:09:47.721500,2018-10-18 18:07:19.944406,debugzSZgD,3.0,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,debug2Ea7T:debugosNZ7,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-18 20:00:26.949390,2018-10-18 20:55:26.773396,debugrWVJB,3.0,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,debugBB0yq:debug30NBt,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-18 23:36:47.846224,2018-10-19 00:26:44.282091,debugPQRfi,3.0,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,debugxH6Hc:debughncuB,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-19 15:32:31.479807,2018-10-19 16:28:34.059428,debugGs8jX,3.0,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,debugbu5Bq:debugl91xD,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-19 18:30:28.663944,2018-10-19 19:16:44.987548,debugsjD9k,3.0,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,debugBhGxH:debugMWNLW,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-19 19:25:39.134717,2018-10-19 20:14:01.652563,debugAVKcW,3.0,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,debug6GN7B:debugBfGog,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-19 20:42:41.578907,2018-10-19 21:30:58.820248,debugU0uFZ,3.0,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,debug5vYxL:debug5nmdy,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-19 22:45:49.525782,2018-10-19 23:34:17.974753,debugt5ypJ,3.0,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,debugdHg9G:debugnb698,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-20 16:57:14.178075,2018-10-20 17:55:32.458968,debugUD0ms,3.0,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,debugXxDJj:debugwfW5a,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-20 19:11:07.473360,2018-10-20 20:01:31.411971,debugII2Xo,3.0,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,debugTFgpv:debugfK2JN,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-20 20:15:28.823106,2018-10-20 21:15:33.010013,debug8lbdL,3.0,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,debugVFMcA:debugjM9rk,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-20 21:22:30.703964,2018-10-20 22:18:55.936915,debugaz6TP,3.0,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79,debugb8Mbo:debugWMuG3,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-19 18:31:19.601051,2018-10-19 19:18:53.588909,debugiEYko,3.0,2.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,debugVzPKf:debugbR0Vq,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-19 20:23:06.091565,2018-10-19 21:29:39.493564,debugol7OU,3.0,2.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81,debugS5d5Q:debugpxU3l,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-20 17:11:15.010873,2018-10-20 18:01:28.914321,debugqqX98,3.0,2.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
82,debugNTcAd:debugiaabY,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-20 18:05:56.447266,2018-10-20 18:56:08.578210,debugJkXTc,3.0,2.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
83,debugVmS30:debugTvoFz,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-20 19:19:01.036352,2018-10-20 20:16:08.648875,debugKZIcf,3.0,2.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,debugmfo3M:debugCN3Vj,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-20 20:20:51.861989,2018-10-20 21:14:59.556348,debugqh216,3.0,2.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
85,debugRNwge:debugv0fyi,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-20 21:28:28.792497,2018-10-20 22:17:39.967758,debug0L0Oy,3.0,2.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86,debugfO0us:debug6tlz1,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-21 23:19:44.803432,2018-10-22 00:23:24.515902,debugrctlv,3.0,2.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
87,debugLou4K:debug5KpMQ,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-22 16:51:53.390057,2018-10-22 17:40:58.713683,debugsx10t,3.0,2.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88,debuglAycr:debugoFV0D,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-22 18:13:19.729907,2018-10-22 19:09:59.702632,debugNgrtk,3.0,2.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
89,debugHNBk3:debugUUMPo,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-22 19:17:01.779509,2018-10-22 20:07:04.697452,debugdWWks,3.0,2.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90,debugohSU7:debugRz3rh,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-22 20:31:44.881569,2018-10-22 21:38:05.206211,debugOWRjW,3.0,2.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
91,debug67jbC:debugFuOd5,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-22 22:23:42.681643,2018-10-22 23:08:59.861848,debugCMbxH,3.0,2.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92,debugWvhTI:debug65Thd,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-22 23:24:13.194309,2018-10-23 00:13:22.782005,debugJF0Wp,3.0,2.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
93,debugm7zD9:debugOLIFw,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-23 18:30:23.839666,2018-10-23 19:29:36.654793,debugf5gky,3.0,2.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
94,debugW3qVn:debugxspIb,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-23 19:42:51.543476,2018-10-23 20:45:55.867094,debugXjUBt,3.0,2.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95,debug89P9i:debugM6pZC,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-23 20:52:09.380476,2018-10-23 21:51:15.973999,debugTCRGh,3.0,2.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,debugTYPE4:debugnAJ5U,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-23 22:58:02.839931,2018-10-23 23:49:14.143795,debugRG2lh,3.0,2.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97,debugoAeJs:debug47jDd,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-28 16:34:32.511568,2018-10-28 17:52:26.238551,debugKK0U7,3.0,2.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,debugAlono:debugbY9Uu,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-28 19:55:23.218881,2018-10-28 20:50:23.398119,debugGBOki,3.0,2.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,debugYsNkJ:debug0AYus,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-28 22:06:57.545411,2018-10-28 23:05:44.007621,debug2D5mC,3.0,2.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100,debugVk1WF:debugksIUE,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-28 23:32:03.505549,2018-10-29 00:23:09.765200,debugBgmvn,3.0,2.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101,debugFL4Kc:debugPi0it,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-29 19:33:26.698755,2018-10-29 20:22:25.611807,debugbe5SC,3.0,2.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
102,debugAN3bL:debugJClT8,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-29 20:47:52.256760,2018-10-29 21:41:34.312890,debugs4E6X,3.0,2.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
103,debugTkyN6:debugdsr6W,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-30 00:34:19.043260,2018-10-30 01:24:36.564559,debugMdey9,3.0,2.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
104,debug5ytRS:debug22nvn,"{'condition': 0, 'counterbalance': 0, 'assignm...",2019-01-31 23:01:12.170466,2019-02-01 00:00:58.271323,debughWKN0,3.0,2.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
105,debugRQQWb:debugwDi2H,"{'condition': 0, 'counterbalance': 0, 'assignm...",2019-02-01 20:24:04.448255,2019-02-01 21:19:38.414725,debugU0Ils,3.0,2.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
106,debugo1MpX:debugfpXYH,"{'condition': 0, 'counterbalance': 0, 'assignm...",2019-02-01 22:48:31.811536,2019-02-01 23:50:55.654008,debugnMToQ,3.0,2.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
107,debugSeRNG:debug5pTo9,"{'condition': 0, 'counterbalance': 0, 'assignm...",2019-02-07 19:29:32.573721,2019-02-07 20:45:06.517044,debugvKGyP,3.0,2.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
108,debug41SJm:debugJW4AU,"{'condition': 0, 'counterbalance': 0, 'assignm...",2019-02-07 21:42:17.424466,2019-02-07 22:30:42.922183,debugWs4e3,3.0,2.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [50]:
newcols = pd.unique(np.concatenate([i.columns.values for i in [preqdf,postqdf]]))

In [94]:
np.unique(preqdf.columns.values)

array(['Are you taking any medications or have you had any recent injuries that could affect your memory or attention? (if so, describe below)',
       'Do you have any hearing or speech impairments?',
       'Do you have normal color vision?', 'Ethnicity',
       'Highest Degree Achieved', 'How alert are you feeling?',
       'How many cups of coffee have you had today?',
       'How many hours of sleep did you get last night?',
       'If yes above, describe',
       'If you are currently an undergraduate, what year are you?',
       'In what year were you born?', 'Is English your first language?',
       'Outside of this study, have you ever watched an episode of either of the TV shows "Atlanta" or "Arrested Development?"',
       'Race (check all that apply)', 'Sex', 'Subject ID', 'Timestamp',
       'What is/was your major?'], dtype=object)