## Imports

In [1]:
import numpy as np
import pandas as pd

from analysis_helpers import Participant
from analysis_helpers.constants import PROCESSED_DIR

## Load data

In [2]:
subid_mapping = Participant.id_mapping
df = pd.read_csv(PROCESSED_DIR / 'questionnaire-data.csv')
df.head()

,uniqueid,beginhit,datastring,testroom,preqtime,Subject ID,"Outside of this study, have you ever watched an episode of either of the TV shows ""Atlanta"" or ""Arrested Development?""",Is English your first language?,Do you have any hearing or speech impairments?,Do you have normal color vision?,...,What is/was your major?,How many hours of sleep did you get last night?,How many cups of coffee have you had today?,How alert are you feeling?,postqtime,How engaging did you find the episode?,How easy/difficult was it to follow the episode?,How well do you feel you recalled the events of the episode?,How well do you feel you learned the characters' names over the course of the episode?,How tired do you feel?
0,debugIEH2T:debugDLVLJ,1539368162836,"{'condition': 0, 'counterbalance': 0, 'assignm...",1,1539368143000,MD-101218-A-01,I've never watched either one,Yes,No,Yes,...,undeclared,7.0,1.0,A little alert,1539371520000,Very engaging,Somewhat easy,Very well,Very well,A little tired
1,debugBUnNA:debugLtZcs,1539371956776,"{'condition': 0, 'counterbalance': 0, 'assignm...",1,1539371933000,MD-101218-B-01,I've never watched either one,Yes,No,Yes,...,undeclared,5.0,0.0,A little sluggish,1539374995000,A little engaging,Somewhat easy,Very well,Somewhat well,A little tired
2,debugYQfMB:debugxg7il,1539372566510,"{'condition': 0, 'counterbalance': 0, 'assignm...",2,1539372538000,MD-101218-A-02,I've never watched either one,Yes,No,Yes,...,undeclared,7.0,2.0,A little alert,1539375570000,Very engaging,Somewhat easy,Somewhat well,Somewhat well,A little tired
3,debugd1YD1:debug4FrAg,1539375821845,"{'condition': 0, 'counterbalance': 0, 'assignm...",1,1539375802000,MD-101218-B-02,I've never watched either one,Yes,No,Yes,...,neuroscience,9.0,0.0,A little alert,1539378568000,Very engaging,Very easy,Very well,Somewhat well,A little alert
4,debug92cgv:debugvdAIT,1539376317256,"{'condition': 0, 'counterbalance': 0, 'assignm...",2,1539376286000,MD-101218-A-03,I've never watched either one,Yes,No,Yes,...,Sociology,7.0,0.0,A little alert,1539379114000,Very engaging,Somewhat easy,Very well,Somewhat well,Very alert

In [3]:
ses1_data = df.loc[df['uniqueid'].isin(subid_mapping['session 1'])]
ses2_data = df.loc[df['uniqueid'].isin(subid_mapping['session 2'])]
assert len(ses1_data) == len(ses2_data) == 53

## Pre-experiment questions

### Previously viewed shows

In [4]:
ses1_data.iloc[:, 6].value_counts(dropna=False).to_frame()

                                                    count
Outside of this study, have you ever watched an...
I've never watched either one                          53

### English first language

In [5]:
ses1_data['Is English your first language?'].value_counts(dropna=False).to_frame()

                                 count
Is English your first language?
Yes                                 53

### Hearing or speech impairments

In [6]:
ses1_data['Do you have any hearing or speech impairments?'].value_counts(dropna=False).to_frame()

                                                count
Do you have any hearing or speech impairments?
No                                                 53

### Normal color vision

In [7]:
ses1_data['Do you have normal color vision?'].value_counts(dropna=False).to_frame()

                                  count
Do you have normal color vision?
Yes                                  53

### Medications & injuries relevant to memory/attention

In [8]:
display(ses1_data.iloc[:, 10].value_counts(dropna=False).to_frame())
ses1_data.iloc[:, 11].value_counts(dropna=False).to_frame()

                                                    count
Are you taking any medications or have you had ...
No                                                     52
Yes                                                     1

                         count
If yes above, describe
NaN                         52
Concussion (April 2015)      1

### Birth year/age

In [9]:
display(ses1_data['In what year were you born?'].value_counts(dropna=False).to_frame())
age = 2018 - ses1_data['In what year were you born?']
summary = age.describe()
summary['std'] = age.std(ddof=0)
summary.to_frame('Age')

                             count
In what year were you born?
1999                            23
2000                            21
1997                             5
1998                             3
1996                             1

            Age
count  53.00000
mean   18.90566
std     0.99554
min    18.00000
25%    18.00000
50%    19.00000
75%    19.00000
max    22.00000

### Sex

In [10]:
display(ses1_data['Sex'].value_counts(dropna=False).to_frame())
nan_sex_subid = ses1_data.loc[pd.isna(ses1_data['Sex']), 'Subject ID'].item()
ses2_data.loc[ses2_data['Subject ID'] == nan_sex_subid, 'Sex'].to_frame()

        count
Sex
Female     40
Male       12
NaN         1

       Sex
35  Female

### Ethnicity

In [11]:
ses1_data['Ethnicity'].value_counts(dropna=False).to_frame()

                        count
Ethnicity
Not Hispanic or Latino     52
Hispanic or Latino          1

### Race

In [12]:
ses1_data['Race (check all that apply)'].str.split(';').explode().value_counts(dropna=False).to_frame()

                                  count
Race (check all that apply)
White                                34
Asian                                16
Black or African American             3
American Indian or Alaska Native      1
other                                 1

In [13]:
ses1_data['Race (check all that apply)'].value_counts(dropna=False).to_frame()

                                        count
Race (check all that apply)
White                                      32
Asian                                      16
Black or African American                   2
American Indian or Alaska Native;White      1
Black or African American;White             1
other                                       1

### Undergraduate class

In [14]:
ses1_data.iloc[:, 17].value_counts(dropna=False).to_frame()

                                                    count
If you are currently an undergraduate, what yea...
'22                                                    32
'21                                                    12
'20                                                     5
'19                                                     4

### Major

In [15]:
ses1_data['What is/was your major?'].str.lower().value_counts(dropna=False).to_frame()

                                                    count
What is/was your major?
undeclared                                             29
psychology                                              5
engineering                                             3
undecided                                               2
english                                                 1
psychology and film                                     1
economics modified with neuroscience                    1
computer science                                        1
environmental studies & neuroscience                    1
undeclared                                              1
anthropology modified with global health                1
neuroscience                                            1
anthropology                                            1
economics/neuroscience                                  1
biology                                                 1
undeclared (but planning on being a psychology ...      1
sociology                                               1
cognitive science                                       1

### Sleep (session 1)

In [16]:
ses1_data['How many hours of sleep did you get last night?'].value_counts(dropna=False).sort_index().to_frame()

                                                 count
How many hours of sleep did you get last night?
5.0                                                  4
6.0                                                 11
6.5                                                  2
7.0                                                 14
8.0                                                 10
8.5                                                  2
9.0                                                  4
9.5                                                  1
10.0                                                 4
11.0                                                 1

In [17]:
summary = ses1_data['How many hours of sleep did you get last night?'].describe()
summary['std'] = ses1_data['How many hours of sleep did you get last night?'].std(ddof=0)
summary.to_frame()

       How many hours of sleep did you get last night?
count                                        53.000000
mean                                          7.367925
std                                           1.434583
min                                           5.000000
25%                                           6.000000
50%                                           7.000000
75%                                           8.000000
max                                          11.000000

### Sleep (session 2)

In [18]:
ses2_data['How many hours of sleep did you get last night?'].value_counts(dropna=False).sort_index().to_frame()

                                                 count
How many hours of sleep did you get last night?
5.0                                                  2
6.0                                                 11
7.0                                                 15
7.5                                                  1
8.0                                                 17
9.0                                                  4
10.0                                                 2
11.0                                                 1

In [19]:
summary = ses2_data['How many hours of sleep did you get last night?'].describe()
summary['std'] = ses2_data['How many hours of sleep did you get last night?'].std(ddof=0)
summary.to_frame()

       How many hours of sleep did you get last night?
count                                        53.000000
mean                                          7.386792
std                                           1.215627
min                                           5.000000
25%                                           7.000000
50%                                           7.000000
75%                                           8.000000
max                                          11.000000

### Coffee (session 1)

In [20]:
ses1_data['How many cups of coffee have you had today?'].value_counts(dropna=False).to_frame()

                                             count
How many cups of coffee have you had today?
0.0                                             36
1.0                                             12
2.0                                              4
3.0                                              1

In [21]:
summary = ses1_data['How many cups of coffee have you had today?'].describe()
summary['std'] = ses1_data['How many cups of coffee have you had today?'].std(ddof=0)
summary.to_frame()

       How many cups of coffee have you had today?
count                                    53.000000
mean                                      0.433962
std                                       0.713996
min                                       0.000000
25%                                       0.000000
50%                                       0.000000
75%                                       1.000000
max                                       3.000000

### Coffee (session 2)

In [22]:
ses2_data['How many cups of coffee have you had today?'].value_counts(dropna=False).to_frame()

                                             count
How many cups of coffee have you had today?
0.0                                             32
1.0                                             17
2.0                                              2
1.5                                              1
3.0                                              1

In [23]:
summary = ses2_data['How many cups of coffee have you had today?'].describe()
summary['std'] = ses2_data['How many cups of coffee have you had today?'].std(ddof=0)
summary.to_frame()

       How many cups of coffee have you had today?
count                                    53.000000
mean                                      0.481132
std                                       0.672662
min                                       0.000000
25%                                       0.000000
50%                                       0.000000
75%                                       1.000000
max                                       3.000000

### Alertness (session 1)

In [24]:
ses1_data['How alert are you feeling?'].value_counts(dropna=False).to_frame()

                            count
How alert are you feeling?
Neutral                        18
A little alert                 15
A little sluggish              14
Very alert                      5
Very sluggish                   1

In [25]:
mapped = ses1_data['How alert are you feeling?'].map({
    'Very sluggish': -2, 
    'A little sluggish': -1, 
    'Neutral': 0, 
    'A little alert': 1, 
    'Very alert': 2
})
summary = mapped.describe()
summary['std'] = mapped.std(ddof=0)
summary.to_frame()

       How alert are you feeling?
count                   53.000000
mean                     0.169811
std                      0.985477
min                     -2.000000
25%                     -1.000000
50%                      0.000000
75%                      1.000000
max                      2.000000

### Alertness (session 2)

In [26]:
ses2_data['How alert are you feeling?'].value_counts(dropna=False).to_frame()

                            count
How alert are you feeling?
Neutral                        23
A little alert                 17
A little sluggish               9
Very alert                      3
Very sluggish                   1

In [27]:
mapped = ses2_data['How alert are you feeling?'].map({
    'Very sluggish': -2, 
    'A little sluggish': -1, 
    'Neutral': 0, 
    'A little alert': 1, 
    'Very alert': 2
})
summary = mapped.describe()
summary['std'] = mapped.std(ddof=0)
summary.to_frame()

       How alert are you feeling?
count                   53.000000
mean                     0.226415
std                      0.860923
min                     -2.000000
25%                      0.000000
50%                      0.000000
75%                      1.000000
max                      2.000000

## Post-experiment questions

### Enagement (session 1)

In [28]:
mapped = ses1_data['How engaging did you find the episode?'].map({
    'Very boring': -2,
    'A little boring': -1,
    'Neutral': 0,
    'A little engaging': 1,
    'Very engaging': 2
})
summary = mapped.describe()
summary['std'] = mapped.std(ddof=0)
summary.to_frame()

       How engaging did you find the episode?
count                               53.000000
mean                                 1.641509
std                                  0.479557
min                                  1.000000
25%                                  1.000000
50%                                  2.000000
75%                                  2.000000
max                                  2.000000

### Easy/difficult to follow (session 1)

In [29]:
mapped = ses1_data['How easy/difficult was it to follow the episode?'].map({
    'Very difficult': -2,
    'Somewhat difficult': -1,
    'Neutral': 0,
    'Somewhat easy': 1,
    'Very easy': 2
})
summary = mapped.describe()
summary['std'] = mapped.std(ddof=0)
summary.to_frame()

       How easy/difficult was it to follow the episode?
count                                         53.000000
mean                                           0.754717
std                                            0.988722
min                                           -1.000000
25%                                            0.000000
50%                                            1.000000
75%                                            1.000000
max                                            2.000000

### Self-reported recall sucess (session 1)

In [30]:
mapped = ses1_data['How well do you feel you recalled the events of the episode?'].map({
    'Not well at all': -2,
    'Not very well': -1,
    'Neutral': 0,
    'Somewhat well': 1,
    'Very well': 2
})
summary = mapped.describe()
summary['std'] = mapped.std(ddof=0)
summary.to_frame()

       How well do you feel you recalled the events of the episode?
count                                          53.000000
mean                                            1.226415
std                                             0.768274
min                                            -1.000000
25%                                             1.000000
50%                                             1.000000
75%                                             2.000000
max                                             2.000000

### Successfully learned characters' names (session 1)

In [31]:
mapped = ses1_data["How well do you feel you learned the characters' names over the course of the episode?"].map({
    'Not well at all': -2,
    'Not very well': -1,
    'Neutral': 0,
    'Somewhat well': 1,
    'Very well': 2
})
summary = mapped.describe()
summary['std'] = mapped.std(ddof=0)
summary.to_frame()

       How well do you feel you learned the characters' names over the course of the episode?
count                                          53.000000
mean                                            0.603774
std                                             0.977861
min                                            -2.000000
25%                                             0.000000
50%                                             1.000000
75%                                             1.000000
max                                             2.000000

### Tiredness (session 1)

In [32]:
mapped = ses1_data['How tired do you feel?'].map({
    'Very tired': -2,
    'A little tired': -1,
    'Neutral': 0,
    'A little alert': 1,
    'Very alert': 2
})
summary = mapped.describe()
summary['std'] = mapped.std(ddof=0)
summary.to_frame()

       How tired do you feel?
count               53.000000
mean                -0.150943
std                  0.978953
min                 -2.000000
25%                 -1.000000
50%                  0.000000
75%                  0.000000
max                  2.000000

### Tiredness (session 2)

In [33]:
mapped = ses2_data['How tired do you feel?'].map({
    'Very tired': -2,
    'A little tired': -1,
    'Neutral': 0,
    'A little alert': 1,
    'Very alert': 2
})
summary = mapped.describe()
summary['std'] = mapped.std(ddof=0)
summary.to_frame()

       How tired do you feel?
count               53.000000
mean                -0.584906
std                  0.878119
min                 -2.000000
25%                 -1.000000
50%                 -1.000000
75%                  0.000000
max                  2.000000

### Inter-session delay period

In [34]:
(
    (
        df.groupby('Subject ID')['preqtime']
        .agg(lambda x: x.max() - x.min()) / 86_400_000
    )
    .agg(['mean', lambda x: x.std(ddof=0)])
    .set_axis(['mean', 'std'])
    .to_frame('inter-session time (days)')
)

      inter-session time (days)
mean                   6.756899
std                    0.724564