## Imports

In [36]:
import numpy as np
import pandas as pd

from analysis_helpers import Participant
from analysis_helpers.constants import PROCESSED_DIR

## Load data

In [53]:
subid_mapping = Participant.id_mapping
df = pd.read_csv(PROCESSED_DIR / 'questionnaire-data.csv')
df.head()

                uniqueid  ...  How tired do you feel?
0  debugIEH2T:debugDLVLJ  ...          A little tired
1  debugBUnNA:debugLtZcs  ...          A little tired
2  debugYQfMB:debugxg7il  ...          A little tired
3  debugd1YD1:debug4FrAg  ...          A little alert
4  debug92cgv:debugvdAIT  ...              Very alert

[5 rows x 28 columns]

In [57]:
ses1_data = df.loc[df['uniqueid'].isin(subid_mapping['session 1'])]
ses2_data = df.loc[df['uniqueid'].isin(subid_mapping['session 2'])]
assert len(ses1_data) == len(ses2_data) == 53

## Pre-experiment questions

### Previously viewed shows

In [103]:
ses1_data.iloc[:, 6].value_counts(dropna=False).to_frame()

                                                    count
Outside of this study, have you ever watched an...
I've never watched either one                          53

### English first language

In [104]:
ses1_data['Is English your first language?'].value_counts(dropna=False).to_frame()

                                 count
Is English your first language?
Yes                                 53

### Hearing or speech impairments

In [105]:
ses1_data['Do you have any hearing or speech impairments?'].value_counts(dropna=False).to_frame()

                                                count
Do you have any hearing or speech impairments?
No                                                 53

### Normal color vision

In [106]:
ses1_data['Do you have normal color vision?'].value_counts(dropna=False).to_frame()

                                  count
Do you have normal color vision?
Yes                                  53

### Medications & injuries relevant to memory/attention

In [108]:
display(ses1_data.iloc[:, 10].value_counts(dropna=False).to_frame())
ses1_data.iloc[:, 11].value_counts(dropna=False).to_frame()

                                                    count
Are you taking any medications or have you had ...
No                                                     52
Yes                                                     1

                         count
If yes above, describe
NaN                         52
Concussion (April 2015)      1

### Birth year/age

In [171]:
display(ses1_data['In what year were you born?'].value_counts(dropna=False).to_frame())
age = 2018 - ses1_data['In what year were you born?']
age.describe().to_frame('Age')

                             count
In what year were you born?
1999                            23
2000                            21
1997                             5
1998                             3
1996                             1

             Age
count  53.000000
mean   18.905660
std     1.005067
min    18.000000
25%    18.000000
50%    19.000000
75%    19.000000
max    22.000000

### Sex

In [172]:
display(ses1_data['Sex'].value_counts(dropna=False).to_frame())
nan_sex_subid = ses1_data.loc[pd.isna(ses1_data['Sex']), 'Subject ID'].item()
ses2_data.loc[ses2_data['Subject ID'] == nan_sex_subid, 'Sex'].to_frame()

        count
Sex
Female     40
Male       12
NaN         1

       Sex
35  Female

### Ethnicity

In [111]:
ses1_data['Ethnicity'].value_counts(dropna=False).to_frame()

                        count
Ethnicity
Not Hispanic or Latino     52
Hispanic or Latino          1

### Race

In [112]:
ses1_data['Race (check all that apply)'].str.split(';').explode().value_counts(dropna=False).to_frame()

                                  count
Race (check all that apply)
White                                34
Asian                                16
Black or African American             3
American Indian or Alaska Native      1
other                                 1

In [175]:
ses1_data['Race (check all that apply)'].value_counts(dropna=False).to_frame()

                                        count
Race (check all that apply)
White                                      32
Asian                                      16
Black or African American                   2
American Indian or Alaska Native;White      1
Black or African American;White             1
other                                       1

### Undergraduate class

In [126]:
ses1_data.iloc[:, 17].value_counts(dropna=False).to_frame()

                                                    count
If you are currently an undergraduate, what yea...
'22                                                    32
'21                                                    12
'20                                                     5
'19                                                     4

### Major

In [157]:
ses1_data['What is/was your major?'].str.lower().value_counts(dropna=False).to_frame()

                                                    count
What is/was your major?
undeclared                                             29
psychology                                              5
engineering                                             3
undecided                                               2
english                                                 1
psychology and film                                     1
economics modified with neuroscience                    1
computer science                                        1
environmental studies & neuroscience                    1
undeclared                                              1
anthropology modified with global health                1
neuroscience                                            1
anthropology                                            1
economics/neuroscience                                  1
biology                                                 1
undeclared (but planning on being a psychology ...      1
sociology                                               1
cognitive science                                       1

### Sleep (session 1)

In [189]:
ses1_data['How many hours of sleep did you get last night?'].value_counts(dropna=False).sort_index().to_frame()

                                                 count
How many hours of sleep did you get last night?
5.0                                                  4
6.0                                                 11
6.5                                                  2
7.0                                                 14
8.0                                                 10
8.5                                                  2
9.0                                                  4
9.5                                                  1
10.0                                                 4
11.0                                                 1

In [184]:
ses1_data['How many hours of sleep did you get last night?'].describe().to_frame()

       How many hours of sleep did you get last night?
count                                        53.000000
mean                                          7.367925
std                                           1.448311
min                                           5.000000
25%                                           6.000000
50%                                           7.000000
75%                                           8.000000
max                                          11.000000

### Sleep (session 2)

In [190]:
ses2_data['How many hours of sleep did you get last night?'].value_counts(dropna=False).sort_index().to_frame()

                                                 count
How many hours of sleep did you get last night?
5.0                                                  2
6.0                                                 11
7.0                                                 15
7.5                                                  1
8.0                                                 17
9.0                                                  4
10.0                                                 2
11.0                                                 1

In [186]:
ses2_data['How many hours of sleep did you get last night?'].describe().to_frame()

       How many hours of sleep did you get last night?
count                                        53.000000
mean                                          7.386792
std                                           1.227261
min                                           5.000000
25%                                           7.000000
50%                                           7.000000
75%                                           8.000000
max                                          11.000000

### Coffee (session 1)

In [191]:
ses1_data['How many cups of coffee have you had today?'].value_counts(dropna=False).to_frame()

                                             count
How many cups of coffee have you had today?
0.0                                             36
1.0                                             12
2.0                                              4
3.0                                              1

In [192]:
ses1_data['How many cups of coffee have you had today?'].describe().to_frame()

       How many cups of coffee have you had today?
count                                    53.000000
mean                                      0.433962
std                                       0.720828
min                                       0.000000
25%                                       0.000000
50%                                       0.000000
75%                                       1.000000
max                                       3.000000

### Coffee (session 2)

In [193]:
ses2_data['How many cups of coffee have you had today?'].value_counts(dropna=False).to_frame()

                                             count
How many cups of coffee have you had today?
0.0                                             32
1.0                                             17
2.0                                              2
1.5                                              1
3.0                                              1

In [194]:
ses2_data['How many cups of coffee have you had today?'].describe().to_frame()

       How many cups of coffee have you had today?
count                                    53.000000
mean                                      0.481132
std                                       0.679099
min                                       0.000000
25%                                       0.000000
50%                                       0.000000
75%                                       1.000000
max                                       3.000000

### Alertness (session 1)

In [203]:
ses1_data['How alert are you feeling?'].value_counts(dropna=False).to_frame()

                            count
How alert are you feeling?
Neutral                        18
A little alert                 15
A little sluggish              14
Very alert                      5
Very sluggish                   1

In [145]:
ses1_data['How alert are you feeling?'].map({
    'Very sluggish': -2, 
    'A little sluggish': -1, 
    'Neutral': 0, 
    'A little alert': 1, 
    'Very alert': 2
}).describe().to_frame()

       How alert are you feeling?
count                   53.000000
mean                     0.169811
std                      0.994907
min                     -2.000000
25%                     -1.000000
50%                      0.000000
75%                      1.000000
max                      2.000000

### Alertness (session 2)

In [204]:
ses2_data['How alert are you feeling?'].value_counts(dropna=False).to_frame()

                            count
How alert are you feeling?
Neutral                        23
A little alert                 17
A little sluggish               9
Very alert                      3
Very sluggish                   1

In [146]:
ses2_data['How alert are you feeling?'].map({
    'Very sluggish': -2, 
    'A little sluggish': -1, 
    'Neutral': 0, 
    'A little alert': 1, 
    'Very alert': 2
}).describe().to_frame()

       How alert are you feeling?
count                   53.000000
mean                     0.226415
std                      0.869162
min                     -2.000000
25%                      0.000000
50%                      0.000000
75%                      1.000000
max                      2.000000

## Post-experiment questions

### Enagement (session 1)

In [152]:
ses1_data['How engaging did you find the episode?'].map({
    'Very boring': -2,
    'A little boring': -1,
    'Neutral': 0,
    'A little engaging': 1,
    'Very engaging': 2
}).describe().to_frame()

       How engaging did you find the episode?
count                               53.000000
mean                                 1.641509
std                                  0.484146
min                                  1.000000
25%                                  1.000000
50%                                  2.000000
75%                                  2.000000
max                                  2.000000

### Easy/difficult to follow (session 1)

In [156]:
ses1_data['How easy/difficult was it to follow the episode?'].map({
    'Very difficult': -2,
    'Somewhat difficult': -1,
    'Neutral': 0,
    'Somewhat easy': 1,
    'Very easy': 2
}).describe().to_frame()

       How easy/difficult was it to follow the episode?
count                                         53.000000
mean                                           0.754717
std                                            0.998184
min                                           -1.000000
25%                                            0.000000
50%                                            1.000000
75%                                            1.000000
max                                            2.000000

### Self-reported recall sucess (session 1)

In [159]:
ses1_data['How well do you feel you recalled the events of the episode?'].map({
    'Not well at all': -2,
    'Not very well': -1,
    'Neutral': 0,
    'Somewhat well': 1,
    'Very well': 2
}).describe().to_frame()

       How well do you feel you recalled the events of the episode?
count                                          53.000000
mean                                            1.226415
std                                             0.775627
min                                            -1.000000
25%                                             1.000000
50%                                             1.000000
75%                                             2.000000
max                                             2.000000

### Successfully learned characters' names (session 1)

In [163]:
ses1_data["How well do you feel you learned the characters' names over the course of the episode?"].map({
    'Not well at all': -2,
    'Not very well': -1,
    'Neutral': 0,
    'Somewhat well': 1,
    'Very well': 2
}).describe().to_frame()

       How well do you feel you learned the characters' names over the course of the episode?
count                                          53.000000
mean                                            0.603774
std                                             0.987219
min                                            -2.000000
25%                                             0.000000
50%                                             1.000000
75%                                             1.000000
max                                             2.000000

### Tiredness (session 1)

In [169]:
ses1_data['How tired do you feel?'].map({
    'Very tired': -2,
    'A little tired': -1,
    'Neutral': 0,
    'A little alert': 1,
    'Very alert': 2
}).describe().to_frame()

       How tired do you feel?
count               53.000000
mean                -0.150943
std                  0.988321
min                 -2.000000
25%                 -1.000000
50%                  0.000000
75%                  0.000000
max                  2.000000

### Tiredness (session 2)

In [170]:
ses2_data['How tired do you feel?'].map({
    'Very tired': -2,
    'A little tired': -1,
    'Neutral': 0,
    'A little alert': 1,
    'Very alert': 2
}).describe().to_frame()

       How tired do you feel?
count               53.000000
mean                -0.584906
std                  0.886522
min                 -2.000000
25%                 -1.000000
50%                 -1.000000
75%                  0.000000
max                  2.000000

### Inter-session delay period

In [202]:
(
    df.groupby('Subject ID')['preqtime'].agg(lambda x: x.max() - x.min()) / 86_400_000
).agg(['mean', 'std']).to_frame('inter-session time (days)')

      inter-session time (days)
mean                   6.756899
std                    0.731498